In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('exports/telco_churn_cleaned.csv')

In [3]:
df.shape

(7032, 21)

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7027,6840-RESVB,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,2234-XADUH,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,4801-JZAZL,Female,No,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,8361-LTMKD,Male,Yes,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,3186-AJIEK,Male,No,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [29]:
total_customers = df.shape[0]
print(f"Total Customers: {total_customers}")

Total Customers: 7032

In [35]:
churned_customers = df[df['Churn']=='Yes'].shape[0]
print(f"Churned Customers: {churned_customers}")

Churned Customers: 1869

In [36]:
churn_rate = (churned_customers/total_customers)*100
print(f"Churn Rate: {round(churn_rate, 2)}%")

Churn Rate: 26.58%

In [37]:
retention_rate = 100-churn_rate
print(f"Retention Rate: {round(retention_rate, 2)}%")

Retention Rate: 73.42%

In [40]:
contract_churn = pd.crosstab(df['Contract'], df['Churn'])
print(contract_churn)

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1306   166
Two year        1637    48

In [41]:
contract_churn['Total'] = contract_churn['No'] + contract_churn['Yes']
contract_churn['Churn Rate (%)'] = round(
    contract_churn['Yes'] / contract_churn['Total'] * 100, 2
)
print(contract_churn)

Churn             No   Yes  Total  Churn Rate (%)
Contract
Month-to-month  2220  1655   3875           42.71
One year        1306   166   1472           11.28
Two year        1637    48   1685            2.85

In [48]:
df['TenureGroup'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 24, 48, 72],
    labels=["0-1 Year", "1-2 Years", "2-4 Years", "4-6 Years"] 
)

In [49]:
tenure_churn = pd.crosstab(df['TenureGroup'], df['Churn'])
tenure_churn['Total'] = tenure_churn['No'] + tenure_churn['Yes']
tenure_churn['Churn Rate (%)'] = round(
    tenure_churn['Yes'] / tenure_churn['Total'] * 100, 2
)
print(tenure_churn)

Churn          No   Yes  Total  Churn Rate (%)
TenureGroup
0-1 Year     1138  1037   2175           47.68
1-2 Years     730   294   1024           28.71
2-4 Years    1269   325   1594           20.39
4-6 Years    2026   213   2239            9.51

In [54]:
monthly_charges = df.groupby('Churn')['MonthlyCharges'].mean()
print(f"Average Monthly Charges: {monthly_charges}")

Average Monthly Charges: Churn
No     61.307408
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [55]:
total_charges = df.groupby('Churn')['TotalCharges'].mean()
print(f"Average Total Charges: {total_charges}")

Average Total Charges: Churn
No     2555.344141
Yes    1531.796094
Name: TotalCharges, dtype: float64